# Generated by Django 5.1.1 on 2024-10-06 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lms_Users',
        ),
    ]
